### ISSUE TITLE
Breaking one block breaks a entire forest. 

### ISSUE THREAD

**Issue by protected22** [Cristichi/CrisTreeCapitator#13] opened 2022-10-27 12:52 UTC
whatever you set as maxium-blocks, even if its only 4 blocks. When using a iron-axe, breaking one log results in breaking a entire forest in a radius of 40 blocks around you.

**Comment by protected22** [comment] 2022-10-27 12:53
This is simmilair to https://github.com/Cristichi/CrisTreeCapitator/issues/2

**Comment by Cristichi** [comment] 2022-10-29 09:22
Hello! I'll take another look into it. But last time I found no problem with the latest build, can you confirm if this is an issue with the latest build? And in which Minecraft version does it happen to you?

**Comment by Cristichi** [comment] 2022-10-31 07:52
Hello! I have rolled a new update, which is under review so it will be published as soon as our folks at curse forge have some time to review it. Could you please try again with the 6.5.6 update once it comes out and see if it solved the issue?

**Comment by Cristichi** [comment] 2022-10-31 08:46
The new update is up. Please update and tell me if it solved the issue. Thank you.

**Comment by Cristichi** [comment] 2022-11-10 10:16
I believe that this issue was solved in the latest version, or that the issue is due to a misconfiguration or happening in an outdated build. Therefore I will close this case as solved, but please do not hesitate to reopen ir or open a new one if you still experience it.

Before closing I want to add that for future reference that the plugin will limit the blocks broken if there is a positive set limit or if axe needed and damage axe are set to true.

**Closed by Cristichi** 2022-11-10 10:16 UTC
